/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmList: typeof import('./components/AlarmList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DisplaySettings: typeof import('./components/DisplaySettings.vue')['default']
    Gain: typeof import('./components/Gain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusLabel: typeof import('./components/StatusLabel.vue')['default']
    TargetActions: typeof import('./components/TargetActions.vue')['default']
    TargetInfo: typeof import('./components/TargetInfo.vue')['default']
    ToggleButton: typeof import('./components/ToggleButton.vue')['default']
  }
}
